version: 2.1

executors:
  java-executor:
    docker:
      - image: gradle:8.12.1-jdk17  # Using Gradle image with Java 17
    working_directory: ~/repo  # Set working directory for the repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout  # Checkout the code from the repo
      - run:
          name: Grant execute permissions to gradlew
          command: chmod +x gradlew  # Allow gradlew to execute
      - run:
          name: Run Tests
          command: ./gradlew clean test  # Run the tests using Gradle
      - run:
          name: Install Argo CD CLI
          command: |
            # Install ArgoCD CLI
            curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.4.8/argocd-linux-amd64
            chmod +x /usr/local/bin/argocd
      - run:
          name: Log into Argo CD and sync the application
          command: |
            # Log into ArgoCD using environment variables
            argocd login $ARGOCD_SERVER --username $ARGOCD_USER --password $ARGOCD_PASSWORD --insecure
            # Sync the application
            argocd app sync salesforce-auto
            # Wait for the app to be in a healthy state
            argocd app wait salesforce-auto --health
      - run:
          name: Upload Test Results to Jira Xray
          command: |
            # Install curl and jq to interact with Jira API
            apt-get update && apt-get install -y curl jq
            # Set Jira Xray API details
            JIRA_URL="https://your-domain.atlassian.net"
            API_TOKEN=$JIRA_API_TOKEN
            USER_EMAIL=$JIRA_USER_EMAIL
            PROJECT_KEY="YOUR_PROJECT_KEY"
            TEST_EXECUTION_KEY="YOUR_TEST_EXECUTION_KEY"
            # Upload Serenity JSON report to Xray
            curl -X POST -H "Content-Type: application/json" \
              -u "$USER_EMAIL:$API_TOKEN" \
              --data @build/serenity-reports/json/*.json \
              "$JIRA_URL/rest/raven/1.0/import/execution"
            echo "Test results uploaded to Jira Xray."

workflows:
  version: 2
  build-and-sync:
    jobs:
      - build  # Run the build job
