version: 2.1  # ✅ Ensure correct version

executors:
  java-executor:
    docker:
      - image: gradle:8.12.1-jdk17
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Grant execute permissions to gradlew
          command: chmod +x gradlew
      - run:
          name: Run Tests
          command: ./gradlew clean test
      - run:
          name: Debug Test Results File
          command: |
            REPORT_PATH="build/reports/cucumber/cucumber.json"
            if [ -f "$REPORT_PATH" ]; then
              echo "✅ Test report found. Checking contents..."
              cat "$REPORT_PATH"
            else
              echo "❌ No test report found!"
              exit 1
            fi
      - run:
          name: Authenticate with Xray Cloud
          command: |
            if [[ -z "$XRAY_CLIENT_ID" || -z "$XRAY_CLIENT_SECRET" ]]; then
              echo "❌ Missing Xray credentials."
              exit 1
            fi
            RESPONSE=$(curl -s -X POST "https://xray.cloud.getxray.app/api/v2/authenticate" \
              -H "Content-Type: application/json" \
              -d "{\"client_id\":\"$XRAY_CLIENT_ID\", \"client_secret\":\"$XRAY_CLIENT_SECRET\"}")
            if [[ $RESPONSE =~ ^\"[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\"$ ]]; then
              XRAY_TOKEN=$(echo "$RESPONSE" | tr -d '"')
              echo "export XRAY_TOKEN=$XRAY_TOKEN" >> $BASH_ENV
              echo "✅ Xray authentication successful."
            else
              echo "❌ Xray authentication failed."
              exit 1
            fi
      - run:
          name: Upload Test Results to Xray Cloud
          command: |
            REPORT_PATH="build/reports/cucumber/cucumber.json"
            if [ -f "$REPORT_PATH" ]; then
              RESPONSE=$(curl -X POST "https://xray.cloud.getxray.app/api/v2/import/execution/cucumber" \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer $XRAY_TOKEN" \
                --data @"$REPORT_PATH")
              echo "Xray Response: $RESPONSE"
              if [[ $RESPONSE == *"key"* ]]; then
                echo "✅ Test results uploaded successfully."
              else
                echo "❌ Xray test upload failed."
                exit 1
              fi
            else
              echo "❌ No test report found!"
              exit 1
            fi
      - run:
          name: Install Argo CD CLI
          command: |
            curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            chmod +x /usr/local/bin/argocd
      - run:
          name: Log into Argo CD and sync the application
          command: |
            argocd login $ARGOCD_SERVER --username $ARGOCD_USER --password $ARGOCD_PASS --grpc-web --insecure
            argocd app sync salesforce-auto
            argocd app wait salesforce-auto --health
      - run:
          name: Create Git Tag
          command: |
            TAG_NAME="v$(date +"%Y%m%d%H%M%S")"
            git tag $TAG_NAME
            git push origin $TAG_NAME
            echo "✅ Created and pushed tag $TAG_NAME"

workflows:
  version: 2.1  # ✅ Ensure correct version
  build-and-sync:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /.*/  # ✅ Runs on all branches