version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:17-jdk
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Set up Gradle
          command: |
            wget https://services.gradle.org/distributions/gradle-8.12.1-bin.zip
            unzip gradle-8.12.1-bin.zip
            export PATH=$PATH:$HOME/gradle-8.12.1/bin
      - run:
          name: Run Tests
          command: ./gradlew test

workflows:
  version: 2
  tag-workflow:
    when:
      tag: /^v\d+\.\d+\.\d+/  # This will trigger for any tags like v1.0.0, v2.3.4, etc.
    jobs:
      - build
