version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/gradle:8.12.1  # Use Gradle Docker image
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout  # Check out the code
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
            - gradle-cache-
      - run:
          name: Run Tests
          command: ./gradlew test  # Run Gradle tests
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

workflows:
  version: 2
  tag-workflow:
    when:
      tag: /^v\d+\.\d+\.\d+/  # This will trigger for tags like v1.0.0, v2.3.4, etc.
    jobs:
      - build
