version: 2.1

executors:
  java-executor:
    docker:
      - image: gradle:8.12.1-jdk17  # Using Gradle image with Java 17
    working_directory: ~/repo  # Set working directory for the repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout  # Checkout the code from the repo

      - run:
          name: Grant execute permissions to gradlew
          command: chmod +x gradlew  # Allow gradlew to execute

      - run:
          name: Run Tests
          command: ./gradlew clean test  # Run the tests using Gradle

      # Authenticate with Xray Cloud
      - run:
          name: Authenticate with Xray Cloud
          command: |
            XRAY_TOKEN=$(curl -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
              -H "Content-Type: application/json" \
              -d "{\"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\"}" | tr -d '"')
            echo "export XRAY_TOKEN=$XRAY_TOKEN" >> $BASH_ENV

      - run:
          name: Upload Test Results to Xray Cloud
          command: |
            # Ensure the report exists
            if [ -f build/reports/cucumber/cucumber.json ]; then
              echo "Uploading test results to Xray Cloud..."
              curl -X POST https://xray.cloud.getxray.app/api/v2/import/execution/cucumber \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer $XRAY_TOKEN" \
                --data @build/reports/cucumber/cucumber.json
              echo "✅ Test results uploaded to Jira Xray Cloud."
            else
              echo "❌ No test report found! Skipping Xray upload."
            fi

      - run:
          name: Install Argo CD CLI
          command: |
            curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            chmod +x /usr/local/bin/argocd

      - run:
          name: Log into Argo CD and sync the application
          command: |
            argocd login $ARGOCD_SERVER --username $ARGOCD_USER --password $ARGOCD_PASS --grpc-web --insecure
            argocd app sync salesforce-auto
            argocd app wait salesforce-auto --health

      - run:
          name: Create Git Tag
          command: |
            TAG_NAME="v$(date +"%Y%m%d%H%M%S")"
            git tag $TAG_NAME
            git push origin $TAG_NAME
            echo "✅ Created and pushed tag $TAG_NAME"

workflows:
  version: 2
  build-and-sync:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
